<?php

$arr = array(
    'fr' => array(
        'Index Page' => 'Sommaire',
        'image' => 'image',
        'Go to cart' => 'Aller au panier',
        'Add' => 'Ajouter',
        'Remove' => 'Supprimer',
        'Cart Page' => 'Panier',
        'name' => 'Nom',
        'Contact details' => 'Détails du contact',
        'Comments' => 'Commentaires',
        'Go to Index' => 'Aller à index',
        'Checkout' => 'Vérifier',
        'Login Page' => 'Page de connexion',
        'Username' => 'Nom de utilisateur',
        'Password' => 'Mot de passe',
        'Login' => 'Connexion',
        'Products page!' => 'Page de produits !',
        'Edit' => 'Éditer',
        'Delete' => 'Effacer',
        'Logout' => 'Se déconnecter',
        'Product Page' => 'Page du produit',
        'Title' => 'Titre',
        'Description' => 'La description',
        'Price' => 'Prix',
        'Image' => 'Image',
        'Products' => 'Des produits',
        'Save' => 'Sauver',
        'View' => 'Vue',
        'Date' => 'Date',
        'Orders Page' => 'Page des commandes',
        'Customer' => 'Client',
        'Adress' => 'Une robe',
        'Total order' => 'Commande totale',
        'Preview order' => 'Aperçu de la commande',
        'Back' => 'Arrière',
        'Order' => 'Ordre',
    ),
);
